# Generated by Django 3.0.2 on 2020-02-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('availableItems', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
        migrations.AddField(
            model_name='order',
            name='listOfProducts',
            field=models.ManyToManyField(to='ToDoApp.Product'),
        ),
    ]
